import type CustomerEntity from '../entities/customer/entity'
export const mockCustomers: CustomerEntity[] = [
    {
        ID: 1,
        name: 'Nguyễn Văn An',
        phone_number: '0901234567',
        date_of_birth: '1990-05-12',
        number_of_oil_changes: 3,
        next_time_change_oil: '2026-09-15',
        status: true,
        action: '',
    },
    {
        ID: 2,
        name: 'Trần Thị Bình',
        phone_number: '0912345678',
        date_of_birth: '1985-08-22',
        number_of_oil_changes: 5,
        next_time_change_oil: '2026-07-10',
        status: true,
        action: '',
    },
    {
        ID: 3,
        name: 'Lê Văn Cường',
        phone_number: '0923456789',
        date_of_birth: null,
        number_of_oil_changes: 1,
        next_time_change_oil: '2026-12-01',
        status: false,
        action: '',
    },
    {
        ID: 4,
        name: 'Phạm Thị Dung',
        phone_number: '0934567890',
        date_of_birth: '1992-11-03',
        number_of_oil_changes: 2,
        next_time_change_oil: '2026-08-20',
        status: true,
        action: '',
    },
    {
        ID: 5,
        name: 'Hoàng Văn Em',
        phone_number: '0945678901',
        date_of_birth: '1988-03-17',
        number_of_oil_changes: 4,
        next_time_change_oil: '2026-05-05',
        status: false,
        action: '',
    },
]
